# Site settings
title: WayneHanley
header-img: img/wh-bg.jpg
email: wayney@gmail.com
copyright_name: Wayne Hanley
description: "Man, Myth, Geek without fear.  Technology advocate, developer, lifter of weights and maker of things."
baseurl: ""
url: "http://waynehanley.com"
twitter_username: WayneHanley
github_username:  WayneHanley
youtube_username: byteyp
email_username:  wayney@gmail.com


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
